version: "3.3"

services:
  #Database
 db:
  image: postgres:${POSTGRES_VERSION}
  container_name: postgres
  restart: always
  environment:
   - POSTGRES_USER=${POSTGRES_USERNAME}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   - POSTGRES_DB=${POSTGRES_DATABASE}
  networks:
   - my_net
  ports:
   - ${POSTGRES_PORT}:5432

  #Database manager
 adminer:
  image: adminer
  container_name: adminer
  restart: always
  networks:
   - my_net
  ports:
   - 8080:8080
  depends_on:
   - db

#  app:
#   build: ./app
#   container_name: app
#   restart: always
#   env_file:
#    - .env
#   networks:
#    - my_net
#   ports:
#    - 80:80
#    - 3000:3000
#    - 3001:3001
#   depends_on:
#    - db

networks:
 my_net:
  driver: bridge
