version: "3.3"

services:
  #Database
 db:
  image: postgres:${POSTGRES_VERSION}
  container_name: postgres
  restart: always
  environment:
   - POSTGRES_USER=${POSTGRES_USERNAME}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   - POSTGRES_DB=${POSTGRES_DATABASE}
  networks:
   - backend
  ports:
   - ${POSTGRES_PORT}:5432

  #Database manager
 adminer:
  image: adminer
  container_name: adminer
  restart: always
  networks:
   - backend
  ports:
   - 8080:8080
  depends_on:
   - db


networks:
 backend:
  driver: bridge
